# Form implementation generated from reading ui file 'addtravels.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_helper3(object):
    def setupUi(self, helper):
        helper.setObjectName("helper")
        helper.resize(719, 203)
        self.centralwidget = QtWidgets.QWidget(parent=helper)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 71, 31))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 60, 121, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 20, 141, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 120, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(540, 20, 141, 31))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(540, 60, 121, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(200, 60, 121, 31))
        self.comboBox.setObjectName("comboBox")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(530, 140, 121, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(510, 100, 201, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(310, 100, 201, 31))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(340, 140, 121, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 60, 121, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        helper.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=helper)
        self.statusbar.setObjectName("statusbar")
        helper.setStatusBar(self.statusbar)

        self.retranslateUi(helper)
        QtCore.QMetaObject.connectSlotsByName(helper)

    def retranslateUi(self, helper):
        _translate = QtCore.QCoreApplication.translate
        helper.setWindowTitle(_translate("helper", "MainWindow"))
        self.label.setText(_translate("helper", "<html><head/><body><p><span style=\" font-size:11pt;\">Марка</span></p></body></html>"))
        self.label_2.setText(_translate("helper", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Водитель</span></p></body></html>"))
        self.label_3.setText(_translate("helper", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Время выезда</span></p></body></html>"))
        self.pushButton.setText(_translate("helper", "Подтвердить"))
        self.label_4.setText(_translate("helper", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Время прибытия</span></p></body></html>"))
        self.label_6.setText(_translate("helper", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Конечный километраж</span></p></body></html>"))
        self.label_7.setText(_translate("helper", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Начальный километраж</span></p></body></html>"))
