# Form implementation generated from reading ui file 'addToCheck.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addToCheck(object):
    def setupUi(self, helper):
        helper.setObjectName("helper")
        helper.resize(797, 203)
        self.centralwidget = QtWidgets.QWidget(parent=helper)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 20, 71, 31))
        self.label.setObjectName("label")
        self.name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name.setGeometry(QtCore.QRect(30, 60, 121, 31))
        self.name.setObjectName("name")
        self.amount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.amount.setGeometry(QtCore.QRect(350, 60, 121, 31))
        self.amount.setObjectName("amount")
        self.price = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.price.setGeometry(QtCore.QRect(190, 60, 121, 31))
        self.price.setObjectName("price")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 20, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 20, 111, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 120, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.otdelNum = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.otdelNum.setGeometry(QtCore.QRect(500, 60, 121, 31))
        self.otdelNum.setObjectName("otdelNum")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 20, 111, 31))
        self.label_4.setObjectName("label_4")
        self.data = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.data.setGeometry(QtCore.QRect(640, 60, 121, 31))
        self.data.setObjectName("data")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(640, 20, 111, 31))
        self.label_5.setObjectName("label_5")
        helper.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=helper)
        self.statusbar.setObjectName("statusbar")
        helper.setStatusBar(self.statusbar)

        self.retranslateUi(helper)
        QtCore.QMetaObject.connectSlotsByName(helper)

    def retranslateUi(self, helper):
        _translate = QtCore.QCoreApplication.translate
        helper.setWindowTitle(_translate("helper", "MainWindow"))
        self.label.setText(_translate("helper", "<html><head/><body><p><span style=\" font-size:11pt;\">Имя</span></p></body></html>"))
        self.label_2.setText(_translate("helper", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Цена</span></p></body></html>"))
        self.label_3.setText(_translate("helper", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Количество</span></p></body></html>"))
        self.pushButton.setText(_translate("helper", "Подтвердить"))
        self.label_4.setText(_translate("helper", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Отдел</span></p></body></html>"))
        self.label_5.setText(_translate("helper", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Дата</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    helper = QtWidgets.QMainWindow()
    ui = Ui_addToCheck()
    ui.setupUi(helper)
    helper.show()
    sys.exit(app.exec())
