# Form implementation generated from reading ui file 'bossWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(982, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.codes = QtWidgets.QWidget()
        self.codes.setObjectName("codes")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.codes)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.codesTable = QtWidgets.QTableWidget(parent=self.codes)
        self.codesTable.setObjectName("codesTable")
        self.codesTable.setColumnCount(0)
        self.codesTable.setRowCount(0)
        self.gridLayout_4.addWidget(self.codesTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.codes, "")
        self.filialGoods = QtWidgets.QWidget()
        self.filialGoods.setObjectName("filialGoods")
        self.filialTable = QtWidgets.QTableWidget(parent=self.filialGoods)
        self.filialTable.setGeometry(QtCore.QRect(0, 10, 931, 541))
        self.filialTable.setObjectName("filialTable")
        self.filialTable.setColumnCount(0)
        self.filialTable.setRowCount(0)
        self.tabWidget.addTab(self.filialGoods, "")
        self.sold = QtWidgets.QWidget()
        self.sold.setObjectName("sold")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.sold)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.soldTable = QtWidgets.QTableWidget(parent=self.sold)
        self.soldTable.setObjectName("soldTable")
        self.soldTable.setColumnCount(0)
        self.soldTable.setRowCount(0)
        self.gridLayout_2.addWidget(self.soldTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.sold, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 982, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuAdd = QtWidgets.QMenu(parent=self.menuBar)
        self.menuAdd.setObjectName("menuAdd")
        MainWindow.setMenuBar(self.menuBar)
        self.movingToFilial = QtGui.QAction(parent=MainWindow)
        self.movingToFilial.setObjectName("movingToFilial")
        self.check = QtGui.QAction(parent=MainWindow)
        self.check.setObjectName("check")
        self.svodNaklad = QtGui.QAction(parent=MainWindow)
        self.svodNaklad.setObjectName("svodNaklad")
        self.log = QtGui.QAction(parent=MainWindow)
        self.log.setObjectName("log")
        self.history = QtGui.QAction(parent=MainWindow)
        self.history.setObjectName("history")
        self.menuAdd.addAction(self.movingToFilial)
        self.menuAdd.addAction(self.check)
        self.menuAdd.addAction(self.svodNaklad)
        self.menuAdd.addAction(self.log)
        self.menuAdd.addAction(self.history)
        self.menuBar.addAction(self.menuAdd.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.codes), _translate("MainWindow", "Товары"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.filialGoods), _translate("MainWindow", "Товары в филиалах"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sold), _translate("MainWindow", "Проданные товары"))
        self.menuAdd.setTitle(_translate("MainWindow", "Действия"))
        self.movingToFilial.setText(_translate("MainWindow", "Переместить в филиал..."))
        self.check.setText(_translate("MainWindow", "Создать чек..."))
        self.svodNaklad.setText(_translate("MainWindow", "Сформировать сводную накладную..."))
        self.log.setText(_translate("MainWindow", "Файл протокола загрузки"))
        self.history.setText(_translate("MainWindow", "Файл истории обмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
