# Form implementation generated from reading ui file 'newCheck.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_newCheck(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.addedGoods = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.addedGoods.setObjectName("addedGoods")
        self.addedGoods.setColumnCount(0)
        self.addedGoods.setRowCount(0)
        self.gridLayout.addWidget(self.addedGoods, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.newItem = QtGui.QAction(parent=MainWindow)
        self.newItem.setObjectName("newItem")
        self.newCheck = QtGui.QAction(parent=MainWindow)
        self.newCheck.setObjectName("newCheck")
        self.menu.addAction(self.newItem)
        self.menu.addAction(self.newCheck)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "Действия"))
        self.newItem.setText(_translate("MainWindow", "Добавить товар..."))
        self.newCheck.setText(_translate("MainWindow", "Создать чек"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_newCheck()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
